#!/usr/bin/env php
<?php
if (!file_exists(dirname(__FILE__) . '/vendor/autoload.php')) {
    echo "> Uh oh, it looks like you forgot to run `composer install`. Please follow the installation instructions at https://github.com/modmore/Gitify/wiki/1.-Installation\n";
    exit (1);
}
require dirname(__FILE__) . '/vendor/autoload.php';

if (version_compare(phpversion(),'5.3.0') >= 0) {
    $tz = @ini_get('date.timezone');
    if (empty($tz)) {
        date_default_timezone_set(@date_default_timezone_get());
    }
}

if (!defined('GITIFY_WORKING_DIR')) {
    define ('GITIFY_WORKING_DIR', $cwd = getcwd() . DIRECTORY_SEPARATOR);
}

use modmore\Gitify\Gitify;
use modmore\Gitify\Command\InitCommand;
use modmore\Gitify\Command\BuildCommand;
use modmore\Gitify\Command\ExtractCommand;
use modmore\Gitify\Command\InstallModxCommand;
use modmore\Gitify\Command\InstallPackageCommand;

$application = new Gitify('Gitify', '0.5.2');
$application->add(new InitCommand);
$application->add(new BuildCommand);
$application->add(new ExtractCommand);
$application->add(new InstallModxCommand);
$application->add(new InstallPackageCommand);
$application->run();
