#!/usr/bin/env php
<?php
$fn = 'Gitify';
$help = "Usage: $fn [command] [options]

Commands:
    init            starts a new Gitify project, creating a .gitify configuration
                    file and optionally installing MODX
    load            loads the MODX site into the repository per the .gitify configuration file
    build           builds the site from the repository into MODX
    install-modx    installs the latest MODX version into the current directory
";

// This file would be something you could run from the command line
// For example:
//
// $ gitify build
//
// which would then build a new MODX site based on what's contained in the gitify repo.
if ($argc < 2) {
    echo $help;
    exit(1);
}


if (version_compare(phpversion(),'5.3.0') >= 0) {
    $tz = @ini_get('date.timezone');
    if (empty($tz)) {
        date_default_timezone_set(@date_default_timezone_get());
    }
}


require_once dirname(__FILE__) . '/src/Gitify.class.php';
$gitify = new Gitify();

$command = $argv[1];
$cwd = getcwd() . DIRECTORY_SEPARATOR;

switch ($command) {
    // starts a new Gitify project
    case 'init':
        require_once dirname(__FILE__) . '/src/GitifyInit.class.php';
        $runner = new GitifyInit();
        $runner->run(array(
            'cwd' => $cwd,
        ));

        break;

    // build the site in MODX
    case 'build':
        if (!file_exists($cwd . '.gitify')) {
            echo "Directory is not a Gitify directory: $cwd\n";
            exit(1);
        }

        $project = $gitify->fromYAML(file_get_contents($cwd . '.gitify'), true);
        if (!$project || !is_array($project)) {
            echo "Error: $cwd.gitify file is not valid YAML, or is empty.\n";
            exit (1);
        }

        $project['cwd'] = $cwd;
        if (!isset($project['path'])) $project['path'] = $cwd;

        require_once dirname(__FILE__) . '/src/GitifyBuild.class.php';
        $runner = new GitifyBuild();
        $runner->run($project);

        break;

    // Load the site into Git
    case 'load':
        if (!file_exists($cwd . '.gitify')) {
            echo "Directory is not a Gitify directory: $cwd\n";
            exit(1);
        }

        $project = $gitify->fromYAML(file_get_contents($cwd . '.gitify'), true);
        if (!$project || !is_array($project)) {
            echo "Error: $cwd.gitify file is not valid YAML, or is empty.\n";
            exit (1);
        }

        $project['cwd'] = $cwd;
        if (!isset($project['path'])) $project['path'] = $cwd;

        require_once dirname(__FILE__) . '/src/GitifyLoad.class.php';
        $runner = new GitifyLoad();
        $runner->run($project);

        break;

    // starts a new Gitify project
    case 'install-modx':
        require_once dirname(__FILE__) . '/src/GitifyInstallMODX.class.php';
        $runner = new GitifyInstallMODX();
        $runner->run(array(
            'cwd' => $cwd,
        ));

        break;

    default:
        echo $help;
        exit(1);
}
