#!/usr/bin/env php
<?php
require 'vendor/autoload.php';

if (version_compare(phpversion(),'5.3.0') >= 0) {
    $tz = @ini_get('date.timezone');
    if (empty($tz)) {
        date_default_timezone_set(@date_default_timezone_get());
    }
}

if (!defined('GITIFY_WORKING_DIR')) {
    define ('GITIFY_WORKING_DIR', $cwd = getcwd() . DIRECTORY_SEPARATOR);
}

use modmore\Gitify\Gitify;
use modmore\Gitify\Command\InitCommand;
use modmore\Gitify\Command\BuildCommand;

$application = new Gitify();
$application->add(new InitCommand);
$application->add(new BuildCommand);
$application->run();
